// GRID PULSE - xoshiro128** PRNG and unbiased uniform sampling.
//
// PURPOSE
//   Implements docs/GAME_CORE.md section 2. This is the device-side counterpart of
//   web/core/rng.js; both are validated against tests/vectors/sequences.json, which
//   is generated by an independent Python implementation neither shares code with.
//
// INVARIANTS
//   - The state advances on EVERY call to Next(), including calls whose result
//     DrawIndex() rejects. Rejected draws consume stream positions. The golden
//     vectors record rejection counts and final state precisely to enforce this.
//   - The all-zero state is absorbing and is guarded against at construction.
//   - DrawIndex() uses rejection sampling, never modulo. Plain `Next() % n` biases
//     low indices; at N=25 the bias is about one part in 2e8 per draw, which is
//     small but real and detectable over a long session by
//     tools/validate_sequence.py.
//
// This header has no Pico SDK dependency, so it compiles for the host and is
// covered by the native test target.

#ifndef GRIDPULSE_RNG_H_
#define GRIDPULSE_RNG_H_

#include <cstdint>

namespace gridpulse {

// One SplitMix32 step. Advances `state` in place and returns the mixed output.
std::uint32_t SplitMix32(std::uint32_t* state);

// Rotate left, 32-bit.
//
// The k == 0 case is handled explicitly. The obvious `(x << k) | (x >> (32 - k))`
// evaluates `x >> 32` when k is zero, which is UNDEFINED BEHAVIOUR for a 32-bit
// type: on x86 the shift count is taken modulo 32 so it silently returns x, on
// ARM it returns 0, and the compiler is entitled to assume it never happens. The
// generator only ever rotates by 7 and 11, so this never fires in production - but a
// utility function that is UB for a legal argument is a trap left lying around for
// the next caller.
constexpr std::uint32_t Rotl32(std::uint32_t x, int k) {
  const unsigned shift = static_cast<unsigned>(k) & 31u;
  return (shift == 0) ? x : ((x << shift) | (x >> (32u - shift)));
}

// Largest multiple of `n` that is <= 2^32. Draws at or above this are rejected.
// Requires a 64-bit intermediate because 2^32 does not fit in 32 bits.
constexpr std::uint64_t RejectionLimit(std::uint32_t n) {
  return (n == 0) ? 0 : (std::uint64_t{1} << 32) - ((std::uint64_t{1} << 32) % n);
}

class Xoshiro128StarStar {
 public:
  // Seeds the four state words by running SplitMix32 over a counter initialised to
  // `seed`, then guards the absorbing all-zero state.
  explicit Xoshiro128StarStar(std::uint32_t seed);

  // Next raw 32-bit output. Always advances the state.
  std::uint32_t Next();

  // Draws uniformly from [0, n). Writes the number of draws rejected before this one
  // succeeded to `rejections` when that pointer is non-null; the count pins the
  // stream position and is compared against the golden vectors.
  //
  // Returns 0 for n == 0 without consuming a draw; callers are expected to have
  // validated the alphabet size long before this point.
  std::uint32_t DrawIndex(std::uint32_t n, std::uint32_t* rejections = nullptr);

  std::uint32_t seed() const { return seed_; }
  const std::uint32_t* state() const { return s_; }

 private:
  std::uint32_t s_[4];
  std::uint32_t seed_;
};

}  // namespace gridpulse

#endif  // GRIDPULSE_RNG_H_
