// Native tests: xoshiro128** and unbiased sampling, against the golden vectors.
//
// The substantive claim being tested is that this C++ implementation produces
// bit-for-bit the same target sequence as web/core/rng.js. Neither was written from
// the other; both are checked against tests/vectors/sequences.json, generated by the
// independent Python reference in tools/refimpl.py. If the two ever diverge, this
// file fails and names the draw index where it first went wrong.

#include "../../firmware/include/board_map.h"
#include "../../firmware/src/pure/crc.h"
#include "../../firmware/src/pure/rng.h"
#include "../vectors/vectors.gen.h"
#include "test_util.h"

using gridpulse::RejectionLimit;
using gridpulse::Rotl32;
using gridpulse::SplitMix32;
using gridpulse::Xoshiro128StarStar;

namespace {

// Renders an index sequence exactly as tools/gen_vectors.py does - comma-joined
// decimal - so the CRC-32 over it is directly comparable. Written into a
// caller-supplied buffer; no allocation.
std::size_t RenderIndices(const std::uint32_t* indices, std::size_t count, char* out,
                          std::size_t capacity) {
  std::size_t length = 0;
  for (std::size_t i = 0; i < count; ++i) {
    if (i != 0) {
      if (length + 1 >= capacity) {
        return 0;
      }
      out[length++] = ',';
    }
    char digits[10];
    std::size_t digit_count = 0;
    std::uint32_t value = indices[i];
    do {
      digits[digit_count++] = static_cast<char>('0' + (value % 10));
      value /= 10;
    } while (value != 0);
    if (length + digit_count >= capacity) {
      return 0;
    }
    while (digit_count > 0) {
      out[length++] = digits[--digit_count];
    }
  }
  return length;
}

// 10 000 indices, at most 2 digits each plus separators.
char g_render_buffer[40000];
std::uint32_t g_indices[10000];

}  // namespace

TEST(Rng, Rotl32Basics) {
  CHECK_EQ_U(Rotl32(0x80000000u, 1), 1u);
  CHECK_EQ_U(Rotl32(0x40000000u, 1), 0x80000000u);
  CHECK_EQ_U(Rotl32(0xDEADBEEFu, 0), 0xDEADBEEFu);
  CHECK_EQ_U(Rotl32(0x00000001u, 31), 0x80000000u);
  // A full rotation is the identity.
  CHECK_EQ_U(Rotl32(Rotl32(0x12345678u, 11), 21), 0x12345678u);
}

TEST(Rng, SplitMix32AdvancesItsCounter) {
  std::uint32_t state = 0;
  SplitMix32(&state);
  CHECK_EQ_U(state, 0x9E3779B9u);
  SplitMix32(&state);
  CHECK_EQ_U(state, 0x9E3779B9u * 2u);
}

TEST(Rng, RejectionLimits) {
  CHECK_EQ_U(RejectionLimit(25), 4294967275ull);
  CHECK_EQ_U(RejectionLimit(3), 4294967295ull);
  CHECK_EQ_U(RejectionLimit(24), 4294967280ull);
  // A power of two divides 2^32 exactly, so nothing is ever rejected.
  CHECK_EQ_U(RejectionLimit(2), 4294967296ull);
  CHECK_EQ_U(RejectionLimit(16), 4294967296ull);
  // Defensive: n == 0 must not divide by zero.
  CHECK_EQ_U(RejectionLimit(0), 0ull);
}

TEST(Rng, RejectionLimitIsAlwaysAMultipleOfN) {
  for (std::uint32_t n = 1; n <= 64; ++n) {
    CHECK_EQ_U(RejectionLimit(n) % n, 0ull);
    // And it is the LARGEST such multiple at or below 2^32.
    CHECK_TRUE(RejectionLimit(n) + n > (1ull << 32));
  }
}

TEST(Rng, AllZeroStateIsGuarded) {
  // No SplitMix32-reachable seed produces an all-zero state, but the guard must
  // exist. Sweep a wide range of seeds and assert the invariant directly.
  for (std::uint32_t seed = 0; seed < 5000; ++seed) {
    Xoshiro128StarStar rng(seed);
    const std::uint32_t* s = rng.state();
    CHECK_TRUE((s[0] | s[1] | s[2] | s[3]) != 0);
  }
}

TEST(Rng, MatchesGoldenVectorsExactly) {
  for (std::size_t c = 0; c < gridpulse_vectors::kSequenceCaseCount; ++c) {
    const auto& vec = gridpulse_vectors::kSequenceCases[c];

    // Raw generator output, isolated from the sampler. A failure here means the
    // 32-bit arithmetic is wrong rather than the rejection logic.
    Xoshiro128StarStar raw_rng(vec.seed);
    for (std::size_t i = 0; i < vec.raw16_count; ++i) {
      CHECK_EQ_U(raw_rng.Next(), vec.raw16[i]);
    }

    // The full draw run.
    Xoshiro128StarStar rng(vec.seed);
    std::uint32_t rejections_total = 0;
    std::uint32_t histogram[gridpulse::kCellCount] = {};
    CHECK_TRUE(vec.draw_count <= sizeof(g_indices) / sizeof(g_indices[0]));

    for (std::uint32_t i = 0; i < vec.draw_count; ++i) {
      std::uint32_t rejections = 0;
      const std::uint32_t index = rng.DrawIndex(vec.n, &rejections);
      rejections_total += rejections;
      g_indices[i] = index;
      CHECK_TRUE(index < vec.n);
      if (index < gridpulse::kCellCount) {
        ++histogram[index];
      }
    }

    // First kPrefixLen indices, explicitly. This localises any divergence.
    for (std::size_t i = 0; i < vec.prefix_count; ++i) {
      CHECK_EQ_U(g_indices[i], vec.prefix[i]);
    }

    // All draw_count indices, via CRC-32 over the canonical rendering.
    const std::size_t rendered = RenderIndices(g_indices, vec.draw_count, g_render_buffer,
                                               sizeof(g_render_buffer));
    CHECK_TRUE(rendered > 0);
    CHECK_EQ_U(gridpulse::Crc32(g_render_buffer, rendered), vec.crc32);

    // Rejected draws still advance the stream, so the count pins the stream
    // position and not merely the emitted values.
    CHECK_EQ_U(rejections_total, vec.rejections);

    // The exact state after the run. Matching this proves the generator was stepped
    // precisely the right number of times.
    for (std::size_t i = 0; i < 4; ++i) {
      CHECK_EQ_U(rng.state()[i], vec.state_after[i]);
    }

    for (std::size_t i = 0; i < vec.histogram_count; ++i) {
      CHECK_EQ_U(histogram[i], vec.histogram[i]);
    }
  }
}

TEST(Rng, DrawIndexIsAlwaysInRange) {
  Xoshiro128StarStar rng(0x13579BDFu);
  bool seen[25] = {};
  for (int i = 0; i < 20000; ++i) {
    const std::uint32_t index = rng.DrawIndex(25);
    CHECK_TRUE(index < 25);
    seen[index] = true;
  }
  for (int i = 0; i < 25; ++i) {
    CHECK_TRUE(seen[i]);
  }
}

TEST(Rng, DrawIndexHandlesDegenerateN) {
  Xoshiro128StarStar rng(1);
  const std::uint32_t* before = rng.state();
  const std::uint32_t snapshot[4] = {before[0], before[1], before[2], before[3]};

  // n == 0 must not divide by zero, and must not consume a draw.
  CHECK_EQ_U(rng.DrawIndex(0), 0u);
  for (std::size_t i = 0; i < 4; ++i) {
    CHECK_EQ_U(rng.state()[i], snapshot[i]);
  }

  // n == 1 always yields 0 and does consume draws.
  for (int i = 0; i < 16; ++i) {
    CHECK_EQ_U(rng.DrawIndex(1), 0u);
  }
}

TEST(Rng, SamplingIsUnbiasedAcrossAWideSweep) {
  // A modulo-biased sampler would over-represent low indices. Over 400 000 draws at
  // N=25 the expected count per index is 16 000 with a standard deviation of about
  // 124, so a 5% band is roughly 6 sigma - wide enough never to flake, tight enough
  // that a real bias would blow straight through it.
  constexpr std::uint32_t kDraws = 400000;
  constexpr std::uint32_t kN = 25;
  std::uint32_t histogram[kN] = {};
  Xoshiro128StarStar rng(0xC0FFEEu);
  for (std::uint32_t i = 0; i < kDraws; ++i) {
    ++histogram[rng.DrawIndex(kN)];
  }
  const double expected = static_cast<double>(kDraws) / kN;
  for (std::uint32_t i = 0; i < kN; ++i) {
    CHECK_NEAR(static_cast<double>(histogram[i]), expected, expected * 0.05);
  }
}

TEST(Rng, ConsecutiveRepeatsOccurAtTheExpectedRate) {
  // Sampling is with replacement and is never resampled to avoid a repeat, so
  // repeats must occur at about 1/N. Their ABSENCE would be the bug: it would mean
  // the sequence is not i.i.d. and leaks information about the next target.
  constexpr std::uint32_t kDraws = 100000;
  constexpr std::uint32_t kN = 25;
  Xoshiro128StarStar rng(0xABCDEF01u);
  std::uint32_t previous = rng.DrawIndex(kN);
  std::uint32_t repeats = 0;
  for (std::uint32_t i = 1; i < kDraws; ++i) {
    const std::uint32_t current = rng.DrawIndex(kN);
    if (current == previous) {
      ++repeats;
    }
    previous = current;
  }
  const double expected = static_cast<double>(kDraws - 1) / kN;
  CHECK_NEAR(static_cast<double>(repeats), expected, expected * 0.10);
}

TEST(Rng, SameSeedReproducesTheRunExactly) {
  // The seed is logged in MODE and END precisely so a run can be reproduced and
  // audited. That is only true if seeding is deterministic.
  Xoshiro128StarStar a(0x5A5A5A5Au);
  Xoshiro128StarStar b(0x5A5A5A5Au);
  for (int i = 0; i < 1000; ++i) {
    CHECK_EQ_U(a.DrawIndex(25), b.DrawIndex(25));
  }
}

TEST(Rng, DifferentSeedsDiverge) {
  Xoshiro128StarStar a(1);
  Xoshiro128StarStar b(2);
  bool differs = false;
  for (int i = 0; i < 64 && !differs; ++i) {
    if (a.Next() != b.Next()) {
      differs = true;
    }
  }
  CHECK_TRUE(differs);
}
