/**
 * GRID PULSE - xoshiro128** PRNG and unbiased uniform sampling.
 *
 * Implements docs/GAME_CORE.md section 2 (spec 1.0.0). Validated against the golden
 * vectors in tests/vectors/sequences.json, which are generated by an independent
 * Python reference implementation (tools/refimpl.py).
 *
 * JAVASCRIPT ARITHMETIC HAZARD
 * ----------------------------
 * This algorithm is defined over unsigned 32-bit integers. JavaScript has neither.
 *   - `a * b` computes in IEEE-754 doubles and silently loses low bits once the
 *     product exceeds 2^53. Every multiplication here MUST use Math.imul, which is
 *     specified to perform exact 32-bit multiplication.
 *   - `<<`, `>>`, `^`, `|` coerce via ToInt32 and yield a SIGNED result, so a value
 *     with bit 31 set comes back negative. Every such expression is normalised with
 *     `>>> 0`.
 *   - `>>` is arithmetic (sign-extending) and would corrupt SplitMix32's mixing. The
 *     logical `>>>` is used throughout.
 *
 * Getting any one of these wrong produces a sequence that looks random and is wrong.
 * That is precisely why the golden vectors exist.
 *
 * No module system: this is a classic script so that web/play.html works from a
 * file:// origin, where ES modules are blocked by CORS.
 */
(function (root, factory) {
  'use strict';
  var GP = root.GridPulse || (root.GridPulse = {});
  factory(GP);
  if (typeof module !== 'undefined' && module.exports) { module.exports = GP; }
})(typeof globalThis !== 'undefined' ? globalThis : this, function (GP) {
  'use strict';

  var TWO_32 = 4294967296;

  /** Rotate a 32-bit value left by k bits. Returns an unsigned 32-bit value. */
  function rotl32(x, k) {
    return (((x << k) | (x >>> (32 - k))) >>> 0);
  }

  /**
   * One SplitMix32 step over a counter.
   * @param {number} state unsigned 32-bit counter
   * @returns {{state: number, value: number}} advanced counter and mixed output
   */
  function splitmix32(state) {
    state = (state + 0x9E3779B9) >>> 0;
    var z = state;
    z = (z ^ (z >>> 16)) >>> 0;
    z = Math.imul(z, 0x21F0AAAD) >>> 0;
    z = (z ^ (z >>> 15)) >>> 0;
    z = Math.imul(z, 0x735A2D97) >>> 0;
    z = (z ^ (z >>> 15)) >>> 0;
    return { state: state, value: z };
  }

  /**
   * xoshiro128** generator.
   *
   * Invariant: the state advances on every nextU32() call, including calls whose
   * result drawIndex() rejects. Rejected draws consume stream positions; the golden
   * vectors record rejection counts and final state specifically to enforce this.
   *
   * @constructor
   * @param {number} seed unsigned 32-bit seed
   */
  function Xoshiro128StarStar(seed) {
    var x = seed >>> 0;
    var s = new Uint32Array(4);
    for (var i = 0; i < 4; i++) {
      var step = splitmix32(x);
      x = step.state;
      s[i] = step.value;
    }
    if ((s[0] | s[1] | s[2] | s[3]) === 0) {
      // Unreachable for any SplitMix32-reachable seed, but the all-zero state is
      // absorbing, so the guard is required by the spec in all implementations.
      s[0] = 1;
    }
    this.s = s;
    this.seed = seed >>> 0;
  }

  /** @returns {number} the next unsigned 32-bit output. */
  Xoshiro128StarStar.prototype.nextU32 = function () {
    var s = this.s;
    var result = Math.imul(rotl32(Math.imul(s[1], 5) >>> 0, 7), 9) >>> 0;
    var t = (s[1] << 9) >>> 0;
    s[2] = (s[2] ^ s[0]) >>> 0;
    s[3] = (s[3] ^ s[1]) >>> 0;
    s[1] = (s[1] ^ s[2]) >>> 0;
    s[0] = (s[0] ^ s[3]) >>> 0;
    s[2] = (s[2] ^ t) >>> 0;
    s[3] = rotl32(s[3], 11);
    return result;
  };

  /** @returns {Array<number>} a copy of s[0..3], for vector comparison. */
  Xoshiro128StarStar.prototype.state = function () {
    return [this.s[0], this.s[1], this.s[2], this.s[3]];
  };

  /**
   * Largest multiple of n that is <= 2^32. Draws at or above this are rejected.
   *
   * Both 2^32 and 2^32 % n are exactly representable as doubles, so this is exact
   * despite not fitting in 32 bits.
   */
  function rejectionLimit(n) {
    if (!(n > 0)) { throw new RangeError('alphabet size must be positive, got ' + n); }
    return TWO_32 - (TWO_32 % n);
  }

  /**
   * Draw one uniform index in [0, n) by rejection sampling.
   *
   * Plain `nextU32() % n` is forbidden: it biases low indices. At N=25 the bias is
   * about one part in 2e8 per draw, which is small but real and would be visible to
   * the chi-square test in tools/validate_sequence.py over a long session.
   *
   * @returns {{index: number, rejections: number}}
   */
  function drawIndex(rng, n) {
    var limit = rejectionLimit(n);
    var rejections = 0;
    for (;;) {
      var r = rng.nextU32();
      if (r < limit) { return { index: r % n, rejections: rejections }; }
      rejections++;
    }
  }

  /**
   * Produce a 32-bit seed from the platform CSPRNG, falling back to a time and
   * Math.random mix if crypto is unavailable (older file:// contexts).
   *
   * Mode B seeds locally because there is no device; Mode A seeds on the RP2040 from
   * its ring oscillator and the host never influences the sequence.
   */
  function randomSeed() {
    var cryptoObj = (typeof globalThis !== 'undefined') ? globalThis.crypto : undefined;
    if (cryptoObj && typeof cryptoObj.getRandomValues === 'function') {
      var buf = new Uint32Array(1);
      cryptoObj.getRandomValues(buf);
      return buf[0] >>> 0;
    }
    var now = (typeof performance !== 'undefined' && performance.now)
      ? performance.now() : 0;
    return ((Math.random() * TWO_32) ^ (now * 1000)) >>> 0;
  }

  GP.rng = {
    Xoshiro128StarStar: Xoshiro128StarStar,
    splitmix32: splitmix32,
    rotl32: rotl32,
    rejectionLimit: rejectionLimit,
    drawIndex: drawIndex,
    randomSeed: randomSeed,
    TWO_32: TWO_32
  };
});
